#!/usr/bin/env ruby
 
require 'date'
require 'rubygems'
require 'RMagick'
 
def get_exif_date(filepath)
  begin
    photo = Magick::Image.read(filepath).first
    dto = photo.get_exif_by_entry('DateTimeOriginal')
    return DateTime.strptime(dto[0][1], '%Y:%m:%d %H:%M:%S')
  rescue
    return nil
  end
end
 
def get_new_file_path(filepath, datetime)
  datetimestr = datetime.strftime('%Y%m%d_%H%M%S')
  #ext = File.extname(filepath)
  #base = File::basename(filepath, extname)
  dir, file = File::split(filepath)
  return "#{dir}/#{datetimestr}_#{file}"
end
 
def rename_by_exif(filepath)
  begin
    datetime = get_exif_date(filepath)
    if datetime != nil
      newfilepath = get_new_file_path(filepath, datetime)
      File.rename(filepath, newfilepath)
      return newfilepath
    else
      return nil
    end
  rescue
    return nil
  end
end
 
ARGV.each{|filepath|
  newfilepath = rename_by_exif(filepath)
  if newfilepath != nil
    # success
    puts "rename: #{filepath} -> #{newfilepath}"
  else
    # failure or untouched
    puts "keep: #{filepath}"
  end
}
 
if ARGV.size < 1
  puts "Usage: #{File.basename(__FILE__)} <files>"
end

